plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'org.dolphinemu.dolphinemu'
    compileSdk 35
    ndkVersion '27.3.13750724'

    defaultConfig {
        minSdk 26
        ndk {
            abiFilters 'arm64-v8a'
        }
        buildConfigField 'String', 'APPLICATION_ID', '"org.dolphinemu.dolphinemu.wn"'
    }

    buildFeatures {
        buildConfig true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }

    packaging {
        jniLibs {
            useLegacyPackaging true
        }
    }

    def dolphinVendorOut = file("$projectDir/vendored/java")

    sourceSets {
        main {
            java.srcDirs += dolphinVendorOut
        }
    }

}

dependencies {
    implementation libs.coreKtx
    implementation libs.activityKtx
    implementation libs.appcompat
}
